### PR TITLE
Update Theia to 0.14.0 and GLSP to 0.7.0

### LINKED ISSUE #109: Update dependencies of GLSP and Theia
Thing besides versions:
@glsp/sprotty-client ->@eclipse-glsp/client
@glsp/theia-integration -> @eclipse-glsp/theia-integration
Server dependencies:
namespace change groupid (com.eclipsesource -> org.eclipse)
artifact id is now full qualified (e.g. glsp-server -> org.eclipse.glsp.server)

make sure to update all necessary version best to check the glsp repo

### PR DESCRIPTION
**Pull request by sgraband**
Updated the Versions. Resolves #109.

Currently i get a error message as described [here](https://spectrum.chat/glsp/general/update-dependencies-of-glsp-and-theia~2a79892d-dfbc-4cc6-8551-644deb813f58).

### CODE REVIEW

**Comment by eneufeld** [comment]
Please updae the Typescript version to at least what is used in theia: https://github.com/eclipse-theia/theia/blob/9fb6351621583f4a3e51954debbea9ed1e080168/package.json#L34
This solved the issue for me

**Comment by sgraband** [comment]
@tortmayr thanks for the fix. Now everthing is working like before.

**Comment by tortmayr** [comment]
@simongraband  Great.  Otherwise the PR looks good to me and would be ready to merge.
However I would like to publish a Release Candidate of the maven glsp packages and use this instead of the snapshot versions to improve stability. Also this ensure that ecore-glsp does not break if we publish an API-breaking change in the glsp nightly version. (Which is very likely to happen from time to time :wink)

I will notify you once the RC is published so you can update the maven dependencies

**Comment by tortmayr** [comment]
@simongraband  The Release Candidate for the maven glsp maven plugins is now deployed. To consume it simply replace "0.7.0-SNAPSHOT" with "0.7.0-RC-01"

**Review by tortmayr — CHANGES_REQUESTED** [review]
@simongraband  The Release Candidate for the  glsp maven plugins is now deployed. To consume it simply replace "0.7.0-SNAPSHOT" with "0.7.0-RC-01"

**Review by tortmayr — APPROVED** [review]

**Pull request merged**
