### PR TITLE
Fix #44: Canvas resets after executing an operation

### LINKED ISSUE #44: Canvas resets after executing an operation
The zoomlevel and offset of the canvas resets after an operation (e.g. move) is executed:
canvas_reset

### PR DESCRIPTION
**Pull request by tortmayr**

### CODE REVIEW

**Review by CamilleLetavernier — CHANGES_REQUESTED** [review]
With this fix, the canvas no longer moves; however when I create new elements (Classes, Attributes), they don't appear on the diagram (Even though they are properly created on the server: if I save & reopen, I can see the new elements)

**Comment by tortmayr** [comment]
You are right. That's strange. I don't see how this change should effect the element creation but I will look into it

**Comment by sgraband** [comment]
I tried this fix again, with the current master, and everything is properly working, until a DataType is added. After that, all newly added Nodes and Edges are not shown on the client. 

I looked into it and it seems that this behavior happens, as soon as [this](https://github.com/eclipsesource/ecore-glsp/blob/92c0158afca41651fb28349db48ba1076b30506c/server/org.eclipse.emfcloud.ecore.glsp/src/main/java/org/eclipse/emfcloud/ecore/glsp/operationhandler/CreateClassifierNodeOperationHandler.java#L83) `createEDataType()` is called. When i change it to `createEClass()` everything works as intended, except for the DataType, obviously.

Do you have any idea what could cause this and how we could work around it?

**Comment by tortmayr** [comment]
Thanks for your investigation Simon! This provided me with the necessary clues to identify the problem. I pushed a new fix for this. Could you please retest this? The problem was a missing id in the GmodelConverter for EDatatypes

**Comment by sgraband** [comment]
Looks good to me 👍 I wasn´t able to find any unintented behavior and the canvas does not reset.

**Review by CamilleLetavernier — APPROVED** [review]

**Pull request merged**
