### PR TITLE
Specify a targetAnchorCorrection Value for ArrowEdges

### LINKED ISSUE #57: Border anchoring is slightly off [1]
The arrow overlaps with the class shape a few pixels:
image

### PR DESCRIPTION
**Pull request by jcebel**
A correction of 3.3 leaves a very small distance between the arrow in the class, but with this value the arrow reaches not to far over the border of the class on hovering (as with 3.0).

In the following I give some example value - if you do not like the current configuration you may choose different ones:

### Correction 3.3
image
image

### Correction 3.5 - does not reach over at all but a slight distance is visible 
image
image

### Correction 3.0 - does reach over - no distance
image
image

Resolves #57

### CODE REVIEW

**Review by CamilleLetavernier — CHANGES_REQUESTED** [review]
The changes look good to me for the EReference. Similar changes should be applied on Generalization links:

image

**Review by CamilleLetavernier — APPROVED** [review]

**Comment by jcebel** [comment]
@CamilleLetavernier Can this be merged? I do not have the rights to do so

**Comment by CamilleLetavernier** [comment]
> Can this be merged? I do not have the rights to do so

Yes, sorry; I wanted to wait for a new build after the merge, but then I forgot about it :)

**Comment by jcebel** [comment]
Why exactly is this failing? Is there something broken in the pipeline? I cannot recreate this locally...

**Comment by CamilleLetavernier** [comment]
> Why exactly is this failing? Is there something broken in the pipeline? I cannot recreate this locally...

Neither can I. It's related to the build of the Electron App; which we'll probably disable because we currently don't need/use it

**Comment by tortmayr** [comment]
@CamilleLetavernier The CI build failed due to a known bug in node-gyp (which is used by theia). This error occurs occasionally but can normally be resolved with a simple rebuild.

CI is now succeful but the CLA check did timeout. Can be merged anyways

**Comment by jcebel** [comment]
So this can be merged now? @tortmayr or @CamilleLetavernier can you do this?

**Pull request merged**
