### PR TITLE
[138] Upgrade to latest GLSP version

### LINKED ISSUE #93: Issue selecting class when creating edges
When creating any edge (e.g. reference) and you select a class and the second class you want to select is below the first class, it is very difficult to select it.
i1

### PR DESCRIPTION
**Pull request by CamilleLetavernier**
Upgrade the Ecore-GLSP dependencies to GLSP 0.8.0-rc1

Note that this doesn't seem to be enough to fix #93

### CODE REVIEW

**Comment by sgraband** [comment]
What should fix #93 is an update of  `@eclipse-glsp/client` in the `client/package.json` like shown [here](https://github.com/eclipsesource/ecore-glsp/commit/a040420b9b49a968e7fad5e1ed145ea50d039c4e#diff-52dbbf94d5c54b68c0cad0702ba94a96L47).

**Comment by CamilleLetavernier** [comment]
Hmm, it looks like I failed my `yarn upgrade` command :) I'll update this

**Comment by CamilleLetavernier** [comment]
That will indeed fix #93, but that means we have to upgrade to the GLSP Nightly version, which requires significant changes compared to 0.8.0rc1. It's gonna take some time... :)

**Comment by CamilleLetavernier** [comment]
The new commit targets GLSP 0.8.0-next/SNAPSHOT rather than 0.8.0-rc1. The change is much more significant.

I still have to investigate a few regressions, but I might have to create follow-up issues for them if they aren't trivial

**Review by tortmayr — APPROVED** [review]
Looks good to me. Core functionality seems to work as expected. Other issues (like css fixes) can be addressed in follow up requests

**Pull request merged**
