### PR TITLE
Renaming attributes(#36)

### PR DESCRIPTION
**Pull request by leodennis**
Fixes renaming attributes issue (#36)

### CODE REVIEW

**Review by tortmayr — CHANGES_REQUESTED** [review]
Thanks! I tested it and the change works mostly great. I only noticed one issue:

An additional "-" is added if I start the rename process, do not change anything and hit enter. 
rename_bug

Please also sign the CLA otherwise we cannot merge this PR.

**Comment by leodennis** [comment]
There are 3 Ways to resolve the duplication of the minus:

- Change sprotty to check for the minus and remove it (so it is not visible in the edit)
- Change the server to ignore a minus at the beginning (it would still be visible in the edit)
- Split EAttribute into 2 labels one with "-" the other with "name : type"

I also decoupled the type which is also duplicated, which is then handled in Issue #37.

**Comment by tortmayr** [comment]
> Change the server to ignore a minus at the beginning (it would still be visible in the edit)

This sound like the best option to me. @planger  What do you think about this?

**Comment by planger** [comment]
> > Change the server to ignore a minus at the beginning (it would still be visible in the edit)
> 
> This sound like the best option to me. @planger What do you think about this?

Yes, sounds good! I'm wondering though whether we should get rid of the `-` altogether, because it may appear like the UML notation for the visibility (`+`, `-`, `~`), which it isn't since Ecore doesn't support visibility anyway. So I'm even proposing to remove the `-`.

**Comment by leodennis** [comment]
Here is how it looks without the minus:
Capture

**Comment by CamilleLetavernier** [comment]
Does Sprotty or GLSP support something like "Display string" vs "Edit string"? If so, I would only use the name of the EAttribute in the "Edit String" (Since the server won't parse the Type anyway, e.g. I don't think typing "attr1 : EInt" would result in changing the type of the EAttribute to EInt).

A more complex option would be to parse the full label on the server side (including the type), but that would be a different feature

> So I'm even proposing to remove the -.

+1

**Comment by planger** [comment]
> Does Sprotty or GLSP support something like "Display string" vs "Edit string"? If so, I would only use the name of the EAttribute in the "Edit String" (Since the server won't parse the Type anyway, e.g. I don't think typing "attr1 : EInt" would result in changing the type of the EAttribute to EInt).

No, it doesn't yet, but maybe a good idea.
 
> A more complex option would be to parse the full label on the server side (including the type), but that would be a different feature

I'm very much in favor of having the server parse the text and then set the corresponding name and type in the Ecore model.
The server can then also only set the display string as a value in the label, which doesn't necessarily have to correspond with the text that was entered by the user during the label edit.

The only GLSP concept that is missing, is that the server sends down a different string that shall be shown in the input element during editing, which would be rather easy to do.

**Comment by leodennis** [comment]
It seems the general tendency was to remove to minus, which then closes this PR.
The changing of the Type can be further discussed in #37 but I would parse the entered type in the edit and set the corresponding type of the EAttribute if it was valid.

**Comment by tortmayr** [comment]
Thanks. Looks good to me now.
I had a weird exception on the server after renaming but this seems to be fixed after I updated the GLSP client dependencies.
 :+1:

**Review by tortmayr — APPROVED** [review]

**Pull request merged**
